language: node_js
node_js:
  - "7"
  - "8"
  - "node"
before_script:
  - 'if [ "$NPM_VERSION" ]; then npm install -g npm@^$NPM_VERSION; fi'
  - 'npm --version'

env:
  - NPM_VERSION=2
  - NPM_VERSION=3

script:
  - npm run test-unit
