language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "node"
before_script:
  - 'if [ "$NPM_VERSION" ]; then npm install -g npm@^$NPM_VERSION; fi'
  - 'npm --version'

env:
  - NPM_VERSION=2
  - NPM_VERSION=3

script:
  - npm run lint
  - npm run test-unit
  - nyc npm run test-unit && nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js
